### ISSUE TITLE
package json needs updated publisher information

### ISSUE THREAD

**Issue by bengreenier** [Azure/platform-chaos#12]
The [package.json](https://github.com/Azure/platform-chaos/blob/master/package.json) file currently still lists `bengreenier` as a publisher, it should instead say `microsoft`.

**Comment by Ethan-Arrowood** [comment]
Can I include this fix in #14 ?

**Comment by bengreenier** [comment]
@Ethan-Arrowood short answer: probably.

longer answer: What i'd ideally like to see if we go that route is clarity at the commit level. You'd want to rebase and merge (not squash and merge) and have one commit that fixes #11 and one that fixes this.

**Comment by Ethan-Arrowood** [comment]
Okay so even though PRs are limited to squash and merging I can (locally) rebase and merge multiple commits in one PR -- I'll go ahead a push to my open pr branch now

**Comment by bengreenier** [comment]
no that isn't necessary - we can modify our github configuration to allow rebase and merge. see https://github.com/orgs/Azure/teams/platform-chaos/discussions/5 for our internal discussion on the matter (sorry folks who don't have visibility here)

**Comment by bengreenier** [comment]
closed in https://github.com/Azure/platform-chaos/pull/19
