### ISSUE TITLE
define auditing chaos event format

### ISSUE THREAD

**Issue by bengreenier** [Azure/platform-chaos#18]
Per internal discussions, there is a large gap in the way in which we provide support for folks running these tools and wishing to understand what chaos is currently occurring in their system. In order to bring clarity to this we must first define a common format for events.

This issue tracks the creation of chaotic events/logging formats. The expectation is that we provide a mechanism for the describing the following scenarios:

+ API or CLI initiates chaos
+ Extension initiates chaos
    + potential downstream logging data about the operation that occurred
+ API or CLI terminates chaos
+ Extension terminates chaos
    + potential downstream logging data about the operation that occurred

Explicitly outside the scope of this is logging system events that occur as the result of a chaotic event. Our expectation is that folks are using an existing production monitoring tool to glean that data.

**Comment by Ethan-Arrowood** [comment]
I've used [`pino`](https://github.com/pinojs/pino) before for logging. It is very fast and has a nice API. Everything is exported in JSON too. Not sure if this exactly what we are looking for but I thought I'd propose it nonetheless.

**Comment by bengreenier** [comment]
Thanks @Ethan-Arrowood - that's an implementation detail, so i'd be relevant over in #22. 👍 

This issue is just for committing to a common format and layout of these events.
