### ISSUE TITLE
auditing support in sdk

### ISSUE THREAD

**Issue by bengreenier** [Azure/platform-chaos#22]
we should add support for simple audit/log generation via our extension sdk. This way folks can call a single method to communicate that their extension has taken some operation, and the status of said operation.

**Comment by bengreenier** [comment]
depends on #18

**Comment by Ethan-Arrowood** [comment]
Proposing we use (`pino`)[https://github.com/pinojs/pino] for this. Good api, very fast, and outputs in JSON
